# Generated by Django 5.1.4 on 2024-12-19 09:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0005_alter_collection_options_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='inventory',
            field=models.PositiveSmallIntegerField(verbose_name=django.core.validators.MinLengthValidator(0, message='You should enter a value more than 0.')),
        ),
        migrations.AlterField(
            model_name='product',
            name='promotions',
            field=models.ManyToManyField(blank=True, related_name='products', to='Store.promotion'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_price',
            field=models.PositiveIntegerField(verbose_name=django.core.validators.MinLengthValidator(1, message='You should enter a value more than 1.')),
        ),
    ]
