# Generated by Django 5.1.4 on 2024-12-19 09:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0006_alter_product_description_alter_product_inventory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='inventory',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinLengthValidator(0, message='You should enter a value more than 0.')]),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_price',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinLengthValidator(1, message='You should enter a value more than 1.')]),
        ),
    ]
