# Generated by Django 5.1.4 on 2024-12-19 09:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0007_alter_product_inventory_alter_product_unit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='inventory',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0, 'You should enter a value more than 0.')]),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_price',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, 'You should enter a value more than 1.')]),
        ),
    ]
